# https://pre-commit.com
default_install_hook_types: [commit-msg, pre-commit]
default_stages: [commit, manual]
fail_fast: true
repos:
  - repo: meta
    hooks:
      - id: check-useless-excludes
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-mock-methods
      - id: python-use-type-annotations
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
      - id: text-unicode-replacement-char
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=4096']
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
        types: [python]
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
        types: [python]
  - repo: local
    hooks:
      - id: absolufy-imports
        name: absolufy-imports
        entry: absolufy-imports
        require_serial: true
        language: system
        types: [python]
      - id: black
        name: black
        entry: black
        require_serial: true
        language: system
        types: [python]
      - id: ruff
        name: ruff
        entry: ruff
        args: ["--fixable=ERA001,F401,F841,T201,T203"]
        require_serial: true
        language: system
        types: [python]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: no-commit-to-branch  # Only check at end of linting
        args: [ '--branch', 'main' ]
