name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test

    steps:
      - uses: actions/checkout@v3
      - name: Set up python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install development dependencies
        run: python -m pip install ".[dev]"

      - name: Run linting checks
        run: invoke lint

      - name: Test the package
        run: invoke test
  